const restroList = [
	{
		info: {
			id: '230460',
			name: 'Nandhana Palace',
			cloudinaryImageId: '195876a3181ef63f76e45e3a7b49b585',
			locality: '3rd Phase',
			areaName: 'Bommasandra',
			costForTwo: '₹500 for two',
			cuisines: ['Biryani', 'Andhra', 'South Indian', 'North Indian'],
			avgRating: 4.2,
			parentId: '2120',
			avgRatingString: '4.2',
			totalRatingsString: '5K+',
			sla: {
				deliveryTime: 23,
				lastMileTravel: 1.8,
				serviceability: 'SERVICEABLE',
				slaString: '23 mins',
				lastMileTravelString: '1.8 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-07 01:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '₹100 OFF',
				subHeader: 'ABOVE ₹179',
				discountTag: 'FLAT DEAL',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/nandhana-palace-3rd-phase-bommasandra-bangalore-230460',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '33724',
			name: 'KFC',
			cloudinaryImageId: 'f01666ac73626461d7455d9c24005cd4',
			locality: 'Attibele Hobli',
			areaName: 'Bommasandra',
			costForTwo: '₹400 for two',
			cuisines: ['Burgers', 'Biryani', 'American', 'Snacks', 'Fast Food'],
			avgRating: 4,
			parentId: '547',
			avgRatingString: '4.0',
			totalRatingsString: '5K+',
			sla: {
				deliveryTime: 27,
				lastMileTravel: 4,
				serviceability: 'SERVICEABLE',
				slaString: '27 mins',
				lastMileTravelString: '4.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '20% OFF',
				subHeader: 'UPTO ₹50',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/kfc-attibele-hobli-bommasandra-bangalore-33724',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '156089',
			name: 'The Good Bowl',
			cloudinaryImageId: '6e04be27387483a7c00444f8e8241108',
			locality: 'Bommasandra',
			areaName: 'Vidyanagar',
			costForTwo: '₹400 for two',
			cuisines: ['Biryani', 'Pastas', 'Punjabi', 'Desserts', 'Beverages'],
			avgRating: 4.3,
			parentId: '7918',
			avgRatingString: '4.3',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 29,
				lastMileTravel: 4,
				serviceability: 'SERVICEABLE',
				slaString: '29 mins',
				lastMileTravelString: '4.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:59:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹100',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/the-good-bowl-bommasandra-vidyanagar-bangalore-156089',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '73044',
			name: 'California Burrito',
			cloudinaryImageId: 'bfc67762fa34dd47250975f3e8131344',
			locality: 'Electronic City',
			areaName: 'Electronic City',
			costForTwo: '₹250 for two',
			cuisines: [
				'Mexican',
				'American',
				'Salads',
				'Continental',
				'Keto',
				'Healthy Food',
			],
			avgRating: 4.5,
			parentId: '1252',
			avgRatingString: '4.5',
			totalRatingsString: '5K+',
			sla: {
				deliveryTime: 33,
				lastMileTravel: 7.6,
				serviceability: 'SERVICEABLE',
				slaString: '33 mins',
				lastMileTravelString: '7.6 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-07 01:00:00',
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: 'guiltfree/GF_Logo_android_3x',
						shortDescription: 'options available',
						fontColor: '#7E808C',
					},
				],
			},
			isOpen: true,
			aggregatedDiscountInfoV2: {},
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: '',
									fontColor: '#7E808C',
									iconId: 'guiltfree/GF_Logo_android_3x',
									shortDescription: 'options available',
								},
							},
						],
					},
				},
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/california-burrito-electronic-city-bangalore-73044',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '264148',
			name: 'Chaayos Chai+Snacks=Relax',
			cloudinaryImageId: 'cace805a6ba74137571d0f7ac92302b1',
			locality: 'Doddathogur',
			areaName: 'Electronic City',
			costForTwo: '₹250 for two',
			cuisines: [
				'Bakery',
				'Beverages',
				'Chaat',
				'Desserts',
				'Home Food',
				'Italian',
				'Maharashtrian',
				'Snacks',
				'Street Food',
				'Sweets',
			],
			avgRating: 4.3,
			parentId: '281782',
			avgRatingString: '4.3',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 36,
				lastMileTravel: 7.9,
				serviceability: 'SERVICEABLE',
				slaString: '36 mins',
				lastMileTravelString: '7.9 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:00:00',
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: 'guiltfree/GF_Logo_android_3x',
						shortDescription: 'options available',
						fontColor: '#7E808C',
					},
				],
			},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: '',
									fontColor: '#7E808C',
									iconId: 'guiltfree/GF_Logo_android_3x',
									shortDescription: 'options available',
								},
							},
						],
					},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '₹125 OFF',
				subHeader: 'ABOVE ₹499',
				discountTag: 'FLAT DEAL',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/chaayos-chai-snacks-relax-doddathogur-electronic-city-bangalore-264148',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '78644',
			name: 'Pizza Hut',
			cloudinaryImageId: '2b4f62d606d1b2bfba9ba9e5386fabb7',
			locality: 'Hosur Main Road',
			areaName: 'Bommasandra',
			costForTwo: '₹350 for two',
			cuisines: ['Pizzas'],
			avgRating: 4.2,
			parentId: '721',
			avgRatingString: '4.2',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 34,
				lastMileTravel: 4,
				serviceability: 'SERVICEABLE',
				slaString: '34 mins',
				lastMileTravelString: '4.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-07 04:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹120',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/pizza-hut-hosur-main-road-bommasandra-bangalore-78644',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '83005',
			name: 'LunchBox - Meals and Thalis',
			cloudinaryImageId: '4edcfc66d91018d69894941ebb3c8d16',
			locality: 'Bommasandra',
			areaName: 'Vidyanagar',
			costForTwo: '₹200 for two',
			cuisines: [
				'Biryani',
				'North Indian',
				'Punjabi',
				'Healthy Food',
				'Desserts',
				'Beverages',
			],
			avgRating: 4.2,
			parentId: '4925',
			avgRatingString: '4.2',
			totalRatingsString: '5K+',
			sla: {
				deliveryTime: 30,
				lastMileTravel: 4,
				serviceability: 'SERVICEABLE',
				slaString: '30 mins',
				lastMileTravelString: '4.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:59:00',
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: 'guiltfree/GF_Logo_android_3x',
						shortDescription: 'options available',
						fontColor: '#7E808C',
					},
				],
			},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: '',
									fontColor: '#7E808C',
									iconId: 'guiltfree/GF_Logo_android_3x',
									shortDescription: 'options available',
								},
							},
						],
					},
				},
			},
			aggregatedDiscountInfoV3: {
				header: 'ITEMS',
				subHeader: 'AT ₹159',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/lunchbox-meals-and-thalis-bommasandra-vidyanagar-bangalore-83005',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '41784',
			name: 'Faasos - Wraps, Rolls & Shawarma',
			cloudinaryImageId: 'af33b81798b11deba338e94b7585d348',
			locality: 'Bommasandra',
			areaName: 'Vidyanagar',
			costForTwo: '₹200 for two',
			cuisines: [
				'Kebabs',
				'Fast Food',
				'Snacks',
				'American',
				'Healthy Food',
				'Desserts',
				'Beverages',
			],
			avgRating: 4.2,
			parentId: '21809',
			avgRatingString: '4.2',
			totalRatingsString: '5K+',
			sla: {
				deliveryTime: 31,
				lastMileTravel: 4,
				serviceability: 'SERVICEABLE',
				slaString: '31 mins',
				lastMileTravelString: '4.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:59:00',
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: 'guiltfree/GF_Logo_android_3x',
						shortDescription: 'options available',
						fontColor: '#7E808C',
					},
				],
			},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: '',
									fontColor: '#7E808C',
									iconId: 'guiltfree/GF_Logo_android_3x',
									shortDescription: 'options available',
								},
							},
						],
					},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹110',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/faasos-wraps-rolls-and-shawarma-bommasandra-vidyanagar-bangalore-41784',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '41788',
			name: 'Oven Story Pizza - Standout Toppings',
			cloudinaryImageId: 'b39e4312ae2e9f65c3b58faaed83f488',
			locality: 'Bommasandra',
			areaName: 'Vidyanagar',
			costForTwo: '₹400 for two',
			cuisines: ['Pizzas', 'Pastas', 'Italian', 'Desserts', 'Beverages'],
			avgRating: 4.5,
			parentId: '3534',
			avgRatingString: '4.5',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 27,
				lastMileTravel: 4,
				serviceability: 'SERVICEABLE',
				slaString: '23-31 mins',
				lastMileTravelString: '4.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:59:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '50% OFF',
				subHeader: 'UPTO ₹100',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/oven-story-pizza-standout-toppings-bommasandra-vidyanagar-bangalore-41788',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '41787',
			name: 'Behrouz Biryani',
			cloudinaryImageId: '89fccaa76f2f760e2742b9e53d32bb69',
			locality: 'Bommasandra',
			areaName: 'Vidyanagar',
			costForTwo: '₹500 for two',
			cuisines: [
				'Biryani',
				'North Indian',
				'Kebabs',
				'Mughlai',
				'Lucknowi',
				'Hyderabadi',
				'Desserts',
				'Beverages',
			],
			avgRating: 4.1,
			parentId: '1803',
			avgRatingString: '4.1',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 31,
				lastMileTravel: 4,
				serviceability: 'SERVICEABLE',
				slaString: '31 mins',
				lastMileTravelString: '4.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:59:00',
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: 'guiltfree/GF_Logo_android_3x',
						shortDescription: 'options available',
						fontColor: '#7E808C',
					},
				],
			},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: '',
									fontColor: '#7E808C',
									iconId: 'guiltfree/GF_Logo_android_3x',
									shortDescription: 'options available',
								},
							},
						],
					},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹100',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/behrouz-biryani-bommasandra-vidyanagar-bangalore-41787',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '41793',
			name: 'Sweet Truth - Cake and Desserts',
			cloudinaryImageId: '81cf6bfe2760a45a0caf2e28716ca4d7',
			locality: 'Bommasandra',
			areaName: 'Vidyanagar',
			costForTwo: '₹450 for two',
			cuisines: ['Snacks', 'Bakery', 'Desserts', 'Beverages'],
			avgRating: 4.2,
			parentId: '4444',
			avgRatingString: '4.2',
			totalRatingsString: '500+',
			sla: {
				deliveryTime: 25,
				lastMileTravel: 4,
				serviceability: 'SERVICEABLE',
				slaString: '25 mins',
				lastMileTravelString: '4.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:59:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹110',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/sweet-truth-cake-and-desserts-bommasandra-vidyanagar-bangalore-41793',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '358341',
			name: 'Truffles',
			cloudinaryImageId: 'cd832b6167eb9f88aeb1ccdebf38d942',
			locality: 'Doddathogur Village',
			areaName: 'Electronic City',
			costForTwo: '₹350 for two',
			cuisines: ['American', 'Beverages', 'Continental', 'Desserts', 'Italian'],
			avgRating: 4.5,
			parentId: '218065',
			avgRatingString: '4.5',
			totalRatingsString: '10K+',
			sla: {
				deliveryTime: 41,
				lastMileTravel: 8.5,
				serviceability: 'SERVICEABLE',
				slaString: '41 mins',
				lastMileTravelString: '8.5 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-07 00:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '₹100 OFF',
				subHeader: 'ABOVE ₹499',
				discountTag: 'FLAT DEAL',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/truffles-doddathogur-village-electronic-city-bangalore-358341',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '392160',
			name: 'Andhra Gunpowder',
			cloudinaryImageId: 'rbptews0ivuaagzgwf8r',
			locality: 'Hebbagodi',
			areaName: 'Electronic City',
			costForTwo: '₹350 for two',
			cuisines: ['Andhra', 'Biryani', 'South Indian'],
			avgRating: 4.4,
			parentId: '10496',
			avgRatingString: '4.4',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 27,
				lastMileTravel: 4.5,
				serviceability: 'SERVICEABLE',
				slaString: '27 mins',
				lastMileTravelString: '4.5 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-07 01:00:00',
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: 'guiltfree/GF_Logo_android_3x',
						shortDescription: 'options available',
						fontColor: '#7E808C',
					},
				],
			},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: '',
									fontColor: '#7E808C',
									iconId: 'guiltfree/GF_Logo_android_3x',
									shortDescription: 'options available',
								},
							},
						],
					},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹100',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/andhra-gunpowder-hebbagodi-electronic-city-bangalore-392160',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '46879',
			name: "McDonald's",
			cloudinaryImageId: 'bb7ae131544c7d37e10fc5faf76f09d6',
			locality: 'Doddatogur Village',
			areaName: 'Electronic City',
			costForTwo: '₹400 for two',
			cuisines: ['Burgers', 'Beverages', 'Cafe', 'Desserts'],
			avgRating: 4.3,
			parentId: '630',
			avgRatingString: '4.3',
			totalRatingsString: '10K+',
			sla: {
				deliveryTime: 37,
				lastMileTravel: 8.3,
				serviceability: 'SERVICEABLE',
				slaString: '37 mins',
				lastMileTravelString: '8.3 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-07 03:45:00',
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: 'guiltfree/GF_Logo_android_3x',
						shortDescription: 'options available',
						fontColor: '#7E808C',
					},
				],
			},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: '',
									fontColor: '#7E808C',
									iconId: 'guiltfree/GF_Logo_android_3x',
									shortDescription: 'options available',
								},
							},
						],
					},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '10% OFF',
				subHeader: 'ABOVE ₹1000',
				discountTag: 'FLAT DEAL',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/mcdonalds-doddatogur-village-electronic-city-bangalore-46879',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '20686',
			name: 'Burger King',
			cloudinaryImageId: 'e33e1d3ba7d6b2bb0d45e1001b731fcf',
			locality: 'Neeladri Road',
			areaName: 'Electronic City',
			costForTwo: '₹350 for two',
			cuisines: ['Burgers', 'American'],
			avgRating: 4.2,
			parentId: '166',
			avgRatingString: '4.2',
			totalRatingsString: '10K+',
			sla: {
				deliveryTime: 38,
				lastMileTravel: 8.6,
				serviceability: 'SERVICEABLE',
				slaString: '38 mins',
				lastMileTravelString: '8.6 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-07 02:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹120',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/burger-king-neeladri-road-electronic-city-bangalore-20686',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '28167',
			name: 'Polar Bear',
			cloudinaryImageId: '57262fe3839f0bff174f3d7e7cc8a2b4',
			locality: '1st Phase',
			areaName: 'Electronic City',
			costForTwo: '₹250 for two',
			cuisines: ['Ice Cream', 'Desserts'],
			avgRating: 4.6,
			veg: true,
			parentId: '726',
			avgRatingString: '4.6',
			totalRatingsString: '10K+',
			sla: {
				deliveryTime: 34,
				lastMileTravel: 8.8,
				serviceability: 'SERVICEABLE',
				slaString: '34 mins',
				lastMileTravelString: '8.8 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:59:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			aggregatedDiscountInfoV2: {},
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/polar-bear-1st-phase-electronic-city-bangalore-28167',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '311239',
			name: 'Keventers - Milkshakes & Desserts',
			cloudinaryImageId: '89707df532fd993b3d79a1a28038a901',
			locality: 'Doddathogur Village',
			areaName: 'Electronic City',
			costForTwo: '₹200 for two',
			cuisines: ['Beverages', 'Ice Cream', 'Desserts', 'Healthy Food'],
			avgRating: 4.1,
			veg: true,
			parentId: '268997',
			avgRatingString: '4.1',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 36,
				lastMileTravel: 7.9,
				serviceability: 'SERVICEABLE',
				slaString: '36 mins',
				lastMileTravelString: '7.9 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-07 03:00:00',
				opened: true,
			},
			badges: {
				textExtendedBadges: [
					{
						iconId: 'guiltfree/GF_Logo_android_3x',
						shortDescription: 'options available',
						fontColor: '#7E808C',
					},
				],
			},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {
						badgeObject: [
							{
								attributes: {
									description: '',
									fontColor: '#7E808C',
									iconId: 'guiltfree/GF_Logo_android_3x',
									shortDescription: 'options available',
								},
							},
						],
					},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '20% OFF',
				subHeader: 'UPTO ₹120',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/keventers-milkshakes-and-desserts-doddathogur-village-electronic-city-bangalore-311239',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '457814',
			name: 'Istah - The Mediterranean Way',
			cloudinaryImageId: '67d4a416bf932f850b0a15ad33aae762',
			locality: 'Begur Hobli',
			areaName: 'Electronic City',
			costForTwo: '₹250 for two',
			cuisines: [
				'Mediterranean',
				'Snacks',
				'Biryani',
				'Grill',
				'Kebabs',
				'Arabian',
				'Lebanese',
				'Beverages',
				'Desserts',
				'Italian',
				'Turkish',
			],
			avgRating: 4.4,
			parentId: '3518',
			avgRatingString: '4.4',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 42,
				lastMileTravel: 8.7,
				serviceability: 'SERVICEABLE',
				slaString: '42 mins',
				lastMileTravelString: '8.7 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:30:00',
				opened: true,
			},
			badges: {
				imageBadges: [
					{
						imageId: 'v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png',
						description: 'OnlyOnSwiggy',
					},
				],
			},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {
						badgeObject: [
							{
								attributes: {
									description: 'OnlyOnSwiggy',
									imageId:
										'v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png',
								},
							},
						],
					},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: 'EVERY ITEM',
				subHeader: '@ ₹139',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/istah-the-mediterranean-way-begur-hobli-electronic-city-bangalore-457814',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '268782',
			name: "Leon's - Burgers & Wings (Leon Grill)",
			cloudinaryImageId: 'b2edbc28b7b8219d6e0a9c049ce06658',
			locality: 'Electronic City',
			areaName: 'Electronic City',
			costForTwo: '₹300 for two',
			cuisines: ['American', 'Snacks', 'Turkish', 'Portuguese', 'Continental'],
			avgRating: 4.3,
			parentId: '371281',
			avgRatingString: '4.3',
			totalRatingsString: '10K+',
			sla: {
				deliveryTime: 39,
				lastMileTravel: 8.4,
				serviceability: 'SERVICEABLE',
				slaString: '39 mins',
				lastMileTravelString: '8.4 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-07 04:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '₹125 OFF',
				subHeader: 'ABOVE ₹349',
				discountTag: 'FLAT DEAL',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/leons-burgers-and-wings-leon-grill-electronic-city-bangalore-268782',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '377552',
			name: 'RNR Biryani - Taste of 1953',
			cloudinaryImageId: 'vcxjzcagtva6yiwa93vz',
			locality: '3rd Phase',
			areaName: 'Electronic City',
			costForTwo: '₹350 for two',
			cuisines: ['Biryani', 'South Indian', 'Kebabs'],
			avgRating: 4.3,
			parentId: '11620',
			avgRatingString: '4.3',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 23,
				lastMileTravel: 1.8,
				serviceability: 'SERVICEABLE',
				slaString: '23 mins',
				lastMileTravelString: '1.8 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-01-06 23:59:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '₹100 OFF',
				subHeader: 'ABOVE ₹179',
				discountTag: 'FLAT DEAL',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/rnr-biryani-taste-of-1953-3rd-phase-electronic-city-bangalore-377552',
			type: 'WEBLINK',
		},
	},
];

export default restroList;